language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install

script:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then npm run build; else echo "not a build branch"; fi
  
deploy:
  - provider: elasticbeanstalk
    region: "eu-central-1"
    app: "wp-client"
    env: "wp-client-esb"
    bucket_name: "elasticbeanstalk-eu-central-1-447041063491"
    bucket_path: "wp-client"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      branch: master

after_deploy:
  - echo "Applcation Deployed!"